{
 "title": "FiveM",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Player count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fxs_player_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connected players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    { "expr": "fxs_player_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections / disconnections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    { "expr": "fxs_player_connections", "legendFormat": "__auto" },
    { "expr": "fxs_player_disconnections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "targets": [
    { "expr": "fxs_average_player_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency (min/max) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    { "expr": "fxs_max_player_ping", "legendFormat": "__auto" },
    { "expr": "fxs_min_player_ping", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Server events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "fxs_events_client", "legendFormat": "__auto" },
    { "expr": "fxs_events_server", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Object count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    { "expr": "fxs_object_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Vehicle Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 24 },
   "targets": [
    { "expr": "fxs_vehicle_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ped count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "targets": [
    { "expr": "fxs_ped_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Object count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fxs_object_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Vehicle count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fxs_vehicle_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ped count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fxs_ped_count", "legendFormat": "__auto" }
   ]
  }
 ]
}